# Source: https://github.com/pharmaverse/admiralci
# Stripped down version of admiralci checks. Good for
# the developement process. When package is ready to
# be published, revisit and add release-related
# workflows.
name: admiral CI/CD Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: admiral-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  R_VERSION: "release"

jobs:
  get_r_version:
    name: Get R version
    runs-on: ubuntu-latest
    outputs:
      r-version: ${{ steps.get_r_version.outputs.R_VERSION }}
    steps:
      - name: Get R Version for Downstream Container Jobs
        id: get_r_version
        run: echo "R_VERSION=$R_VERSION" >> $GITHUB_OUTPUT
        shell: bash
  spellcheck:
    name: Spelling
    uses: ./.github/workflows/spellcheck.yml
    if: github.event_name == 'pull_request'
    needs: get_r_version
    with:
      r-version: "${{ needs.get_r_version.outputs.r-version }}"
  linter:
    name: Lint
    uses: ./.github/workflows/lintr.yml
    needs: get_r_version
    if: github.event_name == 'pull_request'
    with:
      r-version: "${{ needs.get_r_version.outputs.r-version }}"
  man-pages:
    name: Man Pages
    uses: ./.github/workflows/man-pages.yml
    needs: get_r_version
    if: github.event_name == 'pull_request'
    with:
      r-version: "${{ needs.get_r_version.outputs.r-version }}"
    
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: get_r_version
    container:
      image: "ghcr.io/pharmaverse/admiralci-${{ needs.get_r_version.outputs.r-version }}:latest"
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install system dependencies
          run: |
            apt-get install -y --no-install-recommends \
                libudunits2-dev

        - name: Install dependencies
          run: |
            Rscript -e 'remotes::install_deps(dependencies = TRUE)'

        - name: Run tests
          shell: Rscript {0}
          run: |
            devtools::load_all(".")
            devtools::test()
  check:
    name: Check
    uses: ./.github/workflows/r-cmd-check.yml
    if: github.event_name == 'pull_request'
    with:
        error-on: error
